apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: checkoutService
  name: checkoutService
  namespace: online-shop-sandbox
spec:
  replicas: 2
  selector:
    matchLabels:
      app: checkoutService
  template:
    metadata:
      labels:
        app: checkoutService
    spec:
      containers:
        - image: skarnaukhov/sk_test_repository::latest
      name: checkoutService