apiVersion: v1
kind: Service
metadata:
  labels:
    app: checkout-service
  name: checkout-service
  namespace: online-shop-sandbox
spec:
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 31235
  selector:
    app: checkout-service