apiVersion: v1
kind: Service
metadata:
  labels:
    app: checkoutService
  name: checkoutService
spec:
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 31235
  selector:
    app: checkoutService